# This is a basic workflow to help you get started with Actions

name: Build And Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: Get build container
        id: adocbuild
        uses: Miyoshi-Ryota/asciidoctor-action@master
        with:
            # program: "asciidoctor --safe-mode server -a allow-uri-read -r asciidoctor-diagram -o index.html howtocreatebgpd.adoc"
            program: "asciidoctor -a allow-uri-read -a stylesheet=style.css -a styledir=./ -r asciidoctor-diagram -o index.html howtocreatebgpd.adoc"
      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
